/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Part = IDL.Record({
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'bhp' : IDL.Float64,
  'carModel' : IDL.Text,
  'zeroToSixty' : IDL.Float64,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'timestamp' : Time,
  'carMake' : IDL.Text,
  'carYear' : IDL.Nat,
  'stageLevel' : IDL.Nat,
  'torqueNm' : IDL.Float64,
});
export const PriceTier = IDL.Record({
  'stage1' : IDL.Float64,
  'stage2' : IDL.Float64,
  'stage3' : IDL.Opt(IDL.Float64),
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceTiers' : PriceTier,
  'category' : IDL.Text,
});
export const Booking = IDL.Record({
  'customerName' : IDL.Text,
  'carDetails' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : Time,
  'bookingType' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Stats = IDL.Record({
  'avgBhpGain' : IDL.Float64,
  'totalBuilds' : IDL.Nat,
  'customerCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPart' : IDL.Func([Part], [], []),
  'addProject' : IDL.Func([Project], [IDL.Nat], []),
  'addService' : IDL.Func([Service], [], []),
  'featureProject' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getFeaturedProject' : IDL.Func([], [IDL.Opt(Project)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'submitBooking' : IDL.Func([Booking], [IDL.Nat], []),
  'updatePartStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Part = IDL.Record({
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'bhp' : IDL.Float64,
    'carModel' : IDL.Text,
    'zeroToSixty' : IDL.Float64,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'timestamp' : Time,
    'carMake' : IDL.Text,
    'carYear' : IDL.Nat,
    'stageLevel' : IDL.Nat,
    'torqueNm' : IDL.Float64,
  });
  const PriceTier = IDL.Record({
    'stage1' : IDL.Float64,
    'stage2' : IDL.Float64,
    'stage3' : IDL.Opt(IDL.Float64),
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceTiers' : PriceTier,
    'category' : IDL.Text,
  });
  const Booking = IDL.Record({
    'customerName' : IDL.Text,
    'carDetails' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : Time,
    'bookingType' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'avgBhpGain' : IDL.Float64,
    'totalBuilds' : IDL.Nat,
    'customerCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPart' : IDL.Func([Part], [], []),
    'addProject' : IDL.Func([Project], [IDL.Nat], []),
    'addService' : IDL.Func([Service], [], []),
    'featureProject' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getFeaturedProject' : IDL.Func([], [IDL.Opt(Project)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'submitBooking' : IDL.Func([Booking], [IDL.Nat], []),
    'updatePartStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };