/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'customerName' : string,
  'carDetails' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : Time,
  'bookingType' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Part {
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface PriceTier {
  'stage1' : number,
  'stage2' : number,
  'stage3' : [] | [number],
}
export interface Project {
  'id' : bigint,
  'bhp' : number,
  'carModel' : string,
  'zeroToSixty' : number,
  'tags' : Array<string>,
  'description' : string,
  'isFeatured' : boolean,
  'timestamp' : Time,
  'carMake' : string,
  'carYear' : bigint,
  'stageLevel' : bigint,
  'torqueNm' : number,
}
export interface Service {
  'name' : string,
  'description' : string,
  'priceTiers' : PriceTier,
  'category' : string,
}
export interface Stats {
  'avgBhpGain' : number,
  'totalBuilds' : bigint,
  'customerCount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addPart' : ActorMethod<[Part], undefined>,
  'addProject' : ActorMethod<[Project], bigint>,
  'addService' : ActorMethod<[Service], undefined>,
  'featureProject' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllParts' : ActorMethod<[], Array<Part>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getFeaturedProject' : ActorMethod<[], [] | [Project]>,
  'getStats' : ActorMethod<[], Stats>,
  'submitBooking' : ActorMethod<[Booking], bigint>,
  'updatePartStock' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];