/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Part {
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    price: number;
}
export type Time = bigint;
export interface Stats {
    avgBhpGain: number;
    totalBuilds: bigint;
    customerCount: bigint;
}
export interface Service {
    name: string;
    description: string;
    priceTiers: PriceTier;
    category: string;
}
export interface Booking {
    customerName: string;
    carDetails: string;
    email: string;
    message: string;
    preferredDate: Time;
    bookingType: string;
    timestamp: Time;
    phone: string;
}
export interface Project {
    id: bigint;
    bhp: number;
    carModel: string;
    zeroToSixty: number;
    tags: Array<string>;
    description: string;
    isFeatured: boolean;
    timestamp: Time;
    carMake: string;
    carYear: bigint;
    stageLevel: bigint;
    torqueNm: number;
}
export interface PriceTier {
    stage1: number;
    stage2: number;
    stage3?: number;
}
export interface backendInterface {
    addPart(part: Part): Promise<void>;
    addProject(project: Project): Promise<bigint>;
    addService(service: Service): Promise<void>;
    featureProject(projectId: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllParts(): Promise<Array<Part>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllServices(): Promise<Array<Service>>;
    getFeaturedProject(): Promise<Project | null>;
    getStats(): Promise<Stats>;
    submitBooking(booking: Booking): Promise<bigint>;
    updatePartStock(partName: string, inStock: boolean): Promise<void>;
}
import type { PriceTier as _PriceTier, Project as _Project, Service as _Service } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPart(arg0: Part): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPart(arg0);
            return result;
        }
    }
    async addProject(arg0: Project): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0);
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(to_candid_Service_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(to_candid_Service_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async featureProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.featureProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureProject(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllParts(): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParts();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProject(): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProject();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProject();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async submitBooking(arg0: Booking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0);
            return result;
        }
    }
    async updatePartStock(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartStock(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PriceTier_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceTier): PriceTier {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    priceTiers: _PriceTier;
    category: string;
}): {
    name: string;
    description: string;
    priceTiers: PriceTier;
    category: string;
} {
    return {
        name: value.name,
        description: value.description,
        priceTiers: from_candid_PriceTier_n8(_uploadFile, _downloadFile, value.priceTiers),
        category: value.category
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stage1: number;
    stage2: number;
    stage3: [] | [number];
}): {
    stage1: number;
    stage2: number;
    stage3?: number;
} {
    return {
        stage1: value.stage1,
        stage2: value.stage2,
        stage3: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.stage3))
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PriceTier_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceTier): _PriceTier {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    priceTiers: PriceTier;
    category: string;
}): {
    name: string;
    description: string;
    priceTiers: _PriceTier;
    category: string;
} {
    return {
        name: value.name,
        description: value.description,
        priceTiers: to_candid_PriceTier_n3(_uploadFile, _downloadFile, value.priceTiers),
        category: value.category
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stage1: number;
    stage2: number;
    stage3?: number;
}): {
    stage1: number;
    stage2: number;
    stage3: [] | [number];
} {
    return {
        stage1: value.stage1,
        stage2: value.stage2,
        stage3: value.stage3 ? candid_some(value.stage3) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
